# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Design_Project/FromGit/VivadoSDK/project_snake/project_snake.cache/wt [current_project]
set_property parent.project_path D:/Design_Project/FromGit/VivadoSDK/project_snake/project_snake.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/Design_Project/FromGit/VivadoSDK/project_snake/project_snake.srcs/sources_1/new/Generic_counter.v
  D:/Design_Project/FromGit/VivadoSDK/project_snake/project_snake.srcs/sources_1/new/vga_control.v
  D:/Design_Project/FromGit/VivadoSDK/project_snake/project_snake.srcs/sources_1/new/VGA_Wrapper.v
}
synth_design -top VGA_Wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef VGA_Wrapper.dcp
catch { report_utilization -file VGA_Wrapper_utilization_synth.rpt -pb VGA_Wrapper_utilization_synth.pb }
